---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker-jenkins-agent-aws-cli
      image: docker.artifactory.intouchhealth.io/devops/docker-jenkins-aws-encryption-sdk-cli:master-2
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      ports:
        - containerPort: 80
    - name: docker-jenkins-tdh-platform
      image: docker.artifactory.intouchhealth.io/devops/docker-jenkins-tdh-platform:master-18
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: regcreds
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: partition
                operator: In
                values:
                  - spot-agents
                  - regular-agents
  tolerations:
    - key: partition
      operator: Equal
      value: spot-agents
      effect: NoSchedule
    - key: partition
      operator: Equal
      value: regular-agents
      effect: NoSchedule
